# Generated by Django 3.2.7 on 2021-11-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='cant_usuarios',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
