# Generated by Django 3.2.7 on 2021-11-02 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportarProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=False)),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(null=True)),
                ('fechaRespuesta', models.DateField(auto_now_add=True)),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.reportarproblema')),
            ],
        ),
    ]
