# Generated by Django 3.2.7 on 2021-09-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='realizado',
            field=models.BooleanField(default=True),
        ),
    ]
