# Generated by Django 3.2.7 on 2021-10-12 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_auto_20211012_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fechaTermino',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
