# Generated by Django 3.2.7 on 2021-11-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_departamento_cant_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='is_tipo',
            field=models.BooleanField(default=False),
        ),
    ]
