# Generated by Django 3.2.7 on 2021-09-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_alter_tarea_realizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='realizado',
            field=models.BooleanField(default=False),
        ),
    ]
