# Generated by Django 3.2.7 on 2021-10-12 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_tarea_fechatermino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fechaTermino',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
