# Generated by Django 3.2.7 on 2021-12-02 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_tarea_is_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='tarea_subordinada',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='process.tarea'),
        ),
    ]
