# Generated by Django 3.2.7 on 2021-10-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0012_motivorechazo_solucionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivorechazo',
            name='respuesta',
            field=models.TextField(null=True),
        ),
    ]
