# Generated by Django 3.2.7 on 2021-10-21 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0013_motivorechazo_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motivorechazo',
            name='respuesta',
        ),
        migrations.RemoveField(
            model_name='motivorechazo',
            name='solucionado',
        ),
        migrations.CreateModel(
            name='RespuestaRechazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(null=True)),
                ('fechaRespuesta', models.DateField(auto_now_add=True)),
                ('aceptado', models.BooleanField(default=False)),
                ('motivoRechazo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.motivorechazo')),
            ],
        ),
    ]
