# Generated by Django 3.2.7 on 2021-10-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0014_auto_20211021_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivorechazo',
            name='respondido',
            field=models.BooleanField(default=False),
        ),
    ]
