# Generated by Django 3.2.7 on 2021-10-29 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0016_calculoestado_semaforo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculoestado',
            name='diasRestantes',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
