# Generated by Django 3.2.7 on 2021-10-29 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0017_alter_calculoestado_diasrestantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='semaforo',
            name='semaforoVerde',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
    ]
