# Generated by Django 3.2.7 on 2021-10-29 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0018_semaforo_semaforoverde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semaforo',
            name='calculoEstado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.calculoestado'),
        ),
    ]
