# Generated by Django 3.2.7 on 2021-10-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0019_alter_semaforo_calculoestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semaforo',
            name='estadoSemaforo',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
